// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcV_nEzRPhMxt30TCpZp59TkcuqZZ08UQ',
    appId: '1:66129824876:web:a6d48fe500ba68ba761c49',
    messagingSenderId: '66129824876',
    projectId: 'profile-me-72184',
    authDomain: 'profile-me-72184.firebaseapp.com',
    storageBucket: 'profile-me-72184.firebasestorage.app',
    measurementId: 'G-24FZ1HPD5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIXcTMmM1ffsF6ShV2PwE_Ah88iREYZsE',
    appId: '1:66129824876:android:f257eb6220c5f96e761c49',
    messagingSenderId: '66129824876',
    projectId: 'profile-me-72184',
    storageBucket: 'profile-me-72184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABEJlAN-XcWUnOyaeq-SlmmpQ-Y1F6nzk',
    appId: '1:66129824876:ios:903e3b03d176c1f4761c49',
    messagingSenderId: '66129824876',
    projectId: 'profile-me-72184',
    storageBucket: 'profile-me-72184.firebasestorage.app',
    iosBundleId: 'com.example.profileMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABEJlAN-XcWUnOyaeq-SlmmpQ-Y1F6nzk',
    appId: '1:66129824876:ios:903e3b03d176c1f4761c49',
    messagingSenderId: '66129824876',
    projectId: 'profile-me-72184',
    storageBucket: 'profile-me-72184.firebasestorage.app',
    iosBundleId: 'com.example.profileMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcV_nEzRPhMxt30TCpZp59TkcuqZZ08UQ',
    appId: '1:66129824876:web:863f085913a53a7c761c49',
    messagingSenderId: '66129824876',
    projectId: 'profile-me-72184',
    authDomain: 'profile-me-72184.firebaseapp.com',
    storageBucket: 'profile-me-72184.firebasestorage.app',
    measurementId: 'G-5HWB4PGCMY',
  );
}
